# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import pokemon_pb2 as pokemon__pb2


class PokemonStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetByNo = channel.unary_unary(
                '/Pokemon/GetByNo',
                request_serializer=pokemon__pb2.GetByNoReq.SerializeToString,
                response_deserializer=pokemon__pb2.PokemonDetail.FromString,
                )
        self.GetSimpleListByNo = channel.unary_unary(
                '/Pokemon/GetSimpleListByNo',
                request_serializer=pokemon__pb2.GetByNoReq.SerializeToString,
                response_deserializer=pokemon__pb2.PokemonDetail.FromString,
                )


class PokemonServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetByNo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSimpleListByNo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PokemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetByNo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByNo,
                    request_deserializer=pokemon__pb2.GetByNoReq.FromString,
                    response_serializer=pokemon__pb2.PokemonDetail.SerializeToString,
            ),
            'GetSimpleListByNo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSimpleListByNo,
                    request_deserializer=pokemon__pb2.GetByNoReq.FromString,
                    response_serializer=pokemon__pb2.PokemonDetail.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Pokemon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Pokemon(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetByNo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Pokemon/GetByNo',
            pokemon__pb2.GetByNoReq.SerializeToString,
            pokemon__pb2.PokemonDetail.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSimpleListByNo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Pokemon/GetSimpleListByNo',
            pokemon__pb2.GetByNoReq.SerializeToString,
            pokemon__pb2.PokemonDetail.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
