# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokemon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pokemon.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rpokemon.proto\"\x18\n\nGetByNoReq\x12\n\n\x02id\x18\x01 \x01(\x05\")\n\rPokemonDetail\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t2g\n\x07Pokemon\x12(\n\x07GetByNo\x12\x0b.GetByNoReq\x1a\x0e.PokemonDetail\"\x00\x12\x32\n\x11GetSimpleListByNo\x12\x0b.GetByNoReq\x1a\x0e.PokemonDetail\"\x00\x62\x06proto3'
)




_GETBYNOREQ = _descriptor.Descriptor(
  name='GetByNoReq',
  full_name='GetByNoReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GetByNoReq.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=41,
)


_POKEMONDETAIL = _descriptor.Descriptor(
  name='PokemonDetail',
  full_name='PokemonDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PokemonDetail.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='PokemonDetail.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['GetByNoReq'] = _GETBYNOREQ
DESCRIPTOR.message_types_by_name['PokemonDetail'] = _POKEMONDETAIL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetByNoReq = _reflection.GeneratedProtocolMessageType('GetByNoReq', (_message.Message,), {
  'DESCRIPTOR' : _GETBYNOREQ,
  '__module__' : 'pokemon_pb2'
  # @@protoc_insertion_point(class_scope:GetByNoReq)
  })
_sym_db.RegisterMessage(GetByNoReq)

PokemonDetail = _reflection.GeneratedProtocolMessageType('PokemonDetail', (_message.Message,), {
  'DESCRIPTOR' : _POKEMONDETAIL,
  '__module__' : 'pokemon_pb2'
  # @@protoc_insertion_point(class_scope:PokemonDetail)
  })
_sym_db.RegisterMessage(PokemonDetail)



_POKEMON = _descriptor.ServiceDescriptor(
  name='Pokemon',
  full_name='Pokemon',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=86,
  serialized_end=189,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetByNo',
    full_name='Pokemon.GetByNo',
    index=0,
    containing_service=None,
    input_type=_GETBYNOREQ,
    output_type=_POKEMONDETAIL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSimpleListByNo',
    full_name='Pokemon.GetSimpleListByNo',
    index=1,
    containing_service=None,
    input_type=_GETBYNOREQ,
    output_type=_POKEMONDETAIL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POKEMON)

DESCRIPTOR.services_by_name['Pokemon'] = _POKEMON

# @@protoc_insertion_point(module_scope)
